# Data Mining - Lab - 2

#  Numpy  &  Perform Data Exploration with Pandas

-------------------------------------------------------------------------------
## Numpy

1) NumPy (Numerical Python) is a powerful open-source library in Python used for numerical and scientific computing.<br>
2) It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on them efficiently.<br>
3) NumPy is highly optimized and written in C, making it much faster than using regular Python lists for numerical operations.<br>
4) It serves as the foundation for many other Python libraries in data science and machine learning, like pandas, TensorFlow, and scikit-learn.<br>
5) With features like broadcasting, vectorization, and integration with C/C++ code, NumPy allows for cleaner and faster code in numerical computations.<br>



### Step 1. Import the Numpy library

In [1]:
import numpy as np



### Step 2. Create a 1D array of numbers

In [ ]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr2 = np.arange(10) 
# np.arange(15,25)
arr2


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Step 3. Reshape 1D to 2D Array

In [8]:
arr2.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

### Step 4. Create a Linspace array

In [12]:
np.linspace([1,2,3,4,5],stop=3)
np.linspace(10,15)
# default 50 generate thay linspace ma
np.linspace(10,15,10)

array([10.        , 10.55555556, 11.11111111, 11.66666667, 12.22222222,
       12.77777778, 13.33333333, 13.88888889, 14.44444444, 15.        ])

### Step 5. Create a Random Numbered Array

In [ ]:
np.random.rand(10)
np.random.rand(10).reshape(5,2)



array([[0.52232547, 0.45485861],
       [0.26190944, 0.47290684],
       [0.47627329, 0.49977741],
       [0.18837176, 0.35979122],
       [0.26910127, 0.96156119]])

In [19]:
np.random.rand(5,5)


array([[0.62597702, 0.02403652, 0.34168597, 0.92527028, 0.83116104],
       [0.77464858, 0.06586341, 0.68291243, 0.26679643, 0.43134874],
       [0.796818  , 0.93326501, 0.64120455, 0.62090542, 0.64946189],
       [0.67351416, 0.57790853, 0.81852584, 0.78371262, 0.81803222],
       [0.02982652, 0.17184293, 0.85164951, 0.51899314, 0.70618081]])

### Step 6. Create a Random Integer Array

In [32]:
a = np.random.randint(10,20,size=5)
a

array([16, 11, 14, 14, 12], dtype=int32)

In [27]:
a = np.random.randint(10,20,6)
a = np.random.randint(10,20,size=(5,5))
a


array([[15, 15, 10, 15, 17],
       [10, 11, 14, 10, 14],
       [18, 10, 12, 17, 19],
       [14, 16, 16, 13, 13],
       [15, 14, 19, 14, 15]], dtype=int32)

### Step 7. Create a 1D Array and get Max,Min,ArgMax,ArgMin

In [40]:
a = np.random.rand(10,20,5)
a

array([[[5.49589135e-01, 3.59086531e-02, 3.83660365e-01, 3.32375902e-01,
         8.23750346e-01],
        [5.07070739e-01, 5.73332993e-01, 6.80808725e-01, 8.23462258e-01,
         4.31337216e-01],
        [3.51664186e-01, 7.74312155e-01, 6.19230870e-01, 1.28866932e-02,
         7.15794946e-01],
        [7.31445886e-01, 9.63080515e-01, 3.91691202e-01, 2.99260924e-01,
         4.26795439e-02],
        [6.26845930e-02, 9.92596087e-01, 6.37658583e-01, 9.26799607e-01,
         9.01155755e-01],
        [1.58165650e-01, 4.96791581e-01, 8.26188929e-01, 3.41595919e-01,
         8.51177125e-01],
        [2.03449288e-01, 2.05740671e-01, 4.58536810e-01, 1.64623095e-01,
         9.82333938e-01],
        [1.08809262e-01, 7.47181094e-01, 9.66801743e-02, 4.78718236e-01,
         1.42443007e-01],
        [3.86525244e-01, 5.12035826e-02, 3.18368338e-01, 1.24774395e-01,
         1.53310110e-01],
        [8.97728663e-01, 4.77231550e-03, 2.94627922e-02, 3.93149910e-01,
         6.57621200e-01],
        [9

In [42]:
a.max()

np.float64(0.9995298294990507)

In [43]:
a.min()

np.float64(0.0003181950472594952)

In [ ]:
a.argmax()  #give highest value index

np.int64(628)

In [ ]:
a.argmin() #give lowest value index

np.int64(94)

### Step 8. Indexing in 1D Array

In [48]:
arr

array([1, 2, 3, 4, 5])

In [50]:
arr[0] = 10
arr

array([10,  2,  3,  4,  5])

In [59]:
arr[1:4]

array([2, 3, 4])

### Step 9. Indexing in 2D Array

In [54]:
arr2 = arr2.reshape(5,2)
arr2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [58]:
arr2[1][1]

np.int64(3)

### Step 10. Conditional Selection

In [70]:
arr = np.random.randint(20,40,10)
arr

array([36, 39, 38, 39, 31, 29, 39, 26, 25, 23], dtype=int32)

In [74]:
arr>25

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
       False])

In [78]:
arr[(arr>25) & (arr<35)]

array([31, 29, 26], dtype=int32)

### 🔥You did it! 10 exercises down — you're on fire! 🔥

## Pandas



### Step 1. Import the necessary libraries

In [79]:
import pandas as pd 

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user). 

### Step 3. Assign it to a variable called users and use the 'user_id' as index

In [87]:
users = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user",sep='|',index_col='user_id')
users

,age,gender,occupation,zip_code
user_id,,,,
1,24,M,technician,85711
2,53,F,other,94043
3,23,M,writer,32067
4,24,M,technician,43537
5,33,F,other,15213
...,...,...,...,...
939,26,F,student,33319
940,32,M,administrator,02215
941,20,M,student,97229


### Step 4. See the first 25 entries

In [88]:
users.head(25)

,age,gender,occupation,zip_code
user_id,,,,
1,24,M,technician,85711
2,53,F,other,94043
3,23,M,writer,32067
4,24,M,technician,43537
5,33,F,other,15213
6,42,M,executive,98101
7,57,M,administrator,91344
8,36,M,administrator,05201
9,29,M,student,01002


### Step 5. See the last 10 entries

In [89]:
users.tail(10)

,age,gender,occupation,zip_code
user_id,,,,
934,61,M,engineer,22902
935,42,M,doctor,66221
936,24,M,other,32789
937,48,M,educator,98072
938,38,F,technician,55038
939,26,F,student,33319
940,32,M,administrator,02215
941,20,M,student,97229
942,48,F,librarian,78209


### Step 6. What is the number of observations in the dataset?

In [92]:
users.shape[0]

943

### Step 7. What is the number of columns in the dataset?

In [93]:
users.shape[1]

4

### Step 8. Print the name of all the columns.

In [97]:
d = users.columns
d

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

### Step 9. How is the dataset indexed?

In [99]:
e =users.index
e

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       934, 935, 936, 937, 938, 939, 940, 941, 942, 943],
      dtype='int64', name='user_id', length=943)

### Step 10. What is the data type of each column?

In [103]:
users.dtypes

age            int64
gender        object
occupation    object
zip_code      object
dtype: object

### Step 11. Print only the occupation column

In [106]:
users.occupation

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...      
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: object

### Step 12. How many different occupations are in this dataset?

In [113]:
len(users.occupation.unique())
users['occupation'].nunique()

21

### Step 13. What is the most frequent occupation?

In [116]:
users['occupation'].value_counts()

occupation
student          196
other            105
educator          95
administrator     79
engineer          67
programmer        66
librarian         51
writer            45
executive         32
scientist         31
artist            28
technician        27
marketing         26
entertainment     18
healthcare        16
retired           14
lawyer            12
salesman          12
none               9
homemaker          7
doctor             7
Name: count, dtype: int64

In [117]:
users['occupation'].value_counts().head(1)

occupation
student    196
Name: count, dtype: int64

In [118]:
users['occupation'].value_counts().idxmax()

'student'

### Step 14. Summarize the DataFrame.

In [120]:
users.describe()

,age
count,943.000000
mean,34.051962
std,12.192740
min,7.000000
25%,25.000000
50%,31.000000
75%,43.000000
max,73.000000


### Step 15. Summarize all the columns

In [121]:
users.describe(include='all')

,age,gender,occupation,zip_code
count,943.000000,943,943,943
unique,NaN,2,21,795
top,NaN,M,student,55414
freq,NaN,670,196,9
mean,34.051962,NaN,NaN,NaN
std,12.192740,NaN,NaN,NaN
min,7.000000,NaN,NaN,NaN
25%,25.000000,NaN,NaN,NaN
50%,31.000000,NaN,NaN,NaN
75%,43.000000,NaN,NaN,NaN


### Step 16. Summarize only the occupation column

In [124]:
users['occupation'].describe()

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

### Step 17. What is the mean age of users?

In [126]:
users.age.mean()

np.float64(34.05196182396607)

### Step 18. What is the age with least occurrence?

In [127]:
users.age.value_counts().tail()

age
7     1
11    1
66    1
10    1
73    1
Name: count, dtype: int64

In [128]:
users.age.value_counts().idxmin()

np.int64(7)

### You're not just learning, you're mastering it. Keep aiming higher! 🚀